import {
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaArrowDown,
  FaArrowRotateRight,
  FaBars,
  FaCheck,
  FaCircleCheck,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaUpDown,
  FaClock,
  FaRegHeart,
  FaHouse,
  FaMagnifyingGlass,
  FaMinus,
  FaPlus,
  FaPhone,
  FaCartShopping,
  FaRegUser,
  FaCircleXmark,
  FaXmark,
} from "react-icons/fa6";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: FaArrowLeft,
  ArrowRight: FaArrowRight,
  ArrowUp: FaArrowUp,
  ArrowDown: FaArrowDown,
  ArrowPath: FaArrowRotateRight,
  Menu: FaBars,
  Check: FaCheck,
  CheckCircle: FaCircleCheck,
  ChevronDown: FaChevronDown,
  ChevronLeft: FaChevronLeft,
  ChevronRight: FaChevronRight,
  ChevronUp: FaChevronUp,
  ChevronsUpDown: FaUpDown,
  Clock: FaClock,
  Heart: FaRegHeart,
  Home: FaHouse,
  Search: FaMagnifyingGlass,
  Minus: FaMinus,
  Plus: FaPlus,
  Cart: FaCartShopping,
  User: FaRegUser,
  Phone: FaPhone,
  XCircle: FaCircleXmark,
  X: FaXmark,
};
