import {
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiArrowDown,
  FiRefreshCw,
  FiMenu,
  FiCheck,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsUp,
  FiClock,
  FiHeart,
  FiHome,
  FiSearch,
  FiMinus,
  FiPlus,
  FiPhone,
  FiShoppingBag,
  FiUser,
  FiXCircle,
  FiX,
} from "react-icons/fi";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: FiArrowLeft,
  ArrowRight: FiArrowRight,
  ArrowUp: FiArrowUp,
  ArrowDown: FiArrowDown,
  ArrowPath: FiRefreshCw,
  Menu: FiMenu,
  Check: FiCheck,
  CheckCircle: FiCheckCircle,
  ChevronDown: FiChevronDown,
  ChevronLeft: FiChevronLeft,
  ChevronRight: FiChevronRight,
  ChevronUp: FiChevronUp,
  ChevronsUpDown: FiChevronsUp,
  Clock: FiClock,
  Heart: FiHeart,
  Home: FiHome,
  Search: FiSearch,
  Minus: FiMinus,
  Plus: FiPlus,
  Cart: FiShoppingBag,
  User: FiUser,
  Phone: FiPhone,
  XCircle: FiXCircle,
  X: FiX,
};
