import {
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowDown,
  LuRefreshCw,
  LuMenu,
  LuCheck,
  LuCircleCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuChevronsUpDown,
  LuClock,
  LuHeart,
  LuHouse,
  LuSearch,
  LuMinus,
  LuPlus,
  LuPhone,
  LuShoppingBag,
  LuUser,
  LuCircleX,
  LuX,
} from "react-icons/lu";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: LuArrowLeft,
  ArrowRight: LuArrowRight,
  ArrowUp: LuArrowUp,
  ArrowDown: LuArrowDown,
  ArrowPath: LuRefreshCw,
  Menu: LuMenu,
  Check: LuCheck,
  CheckCircle: LuCircleCheck,
  ChevronDown: LuChevronDown,
  ChevronLeft: LuChevronLeft,
  ChevronRight: LuChevronRight,
  ChevronUp: LuChevronUp,
  ChevronsUpDown: LuChevronsUpDown,
  Clock: LuClock,
  Heart: LuHeart,
  Home: LuHouse,
  Search: LuSearch,
  Minus: LuMinus,
  Plus: LuPlus,
  Cart: LuShoppingBag,
  User: LuUser,
  Phone: LuPhone,
  XCircle: LuCircleX,
  X: LuX,
};
